The best creative tab
EndersMagic/EnderMagic pull request #66
Opened 2020-10-03 18:12 UTC by GoogeTan

Added cort button to creative tab.
Fixed creative search

2020-10-03 23:29 UTC, hohserg1 requested changes
Попробуй сделать отдельную кнопку-переключатель для каждой категории

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +        return mouseX >= this.x && mouseX < this.x + this.width && mouseY >= this.y && mouseY < this.y + this.height;
Стоит вынести одинаковое вычисление в переменную

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +        System.out.println(mouseX >= this.x && mouseX < this.x + this.width && mouseY >= this.y && mouseY < this.y + this.height);
После того, как код стал рабочим, стоит удалять дебажные println

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +    public EMTextField(int componentId, FontRenderer fontrendererObj, int x, int y, int width, int height, GuiContainerCreative gui)
![image](https://user-images.githubusercontent.com/35610168/95003362-49486e80-05e7-11eb-8ac5-f5dec8ec9825.png)
Может, стоит сделать строку поиска светлой?
У строки поиска не выровнен правый край.
Пример в ванили:
![image](https://user-images.githubusercontent.com/35610168/95003392-7f85ee00-05e7-11eb-95f6-96b611172c12.png)

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/init/EMEvents.java
> +                    text.x, text.y, text.width, text.height,(GuiContainerCreative) event.getGui());
Стоит сделать extract variable на выражении `((GuiContainerCreative) event.getGui())`
Может, лучше перенести эту логику в GuiContainerCreativeEM?

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/init/EMEvents.java
> +            event.getButtonList().add(new GuiButtonSort(15, 8, 4, 10, 10, "", (GuiContainerCreative) event.getGui()));
Почему buttonId==15? Откуда это магическое число?

2020-10-03 23:29 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/util/GuiContainerCreativeEM.java
> +        buttonList.add(new GuiButtonSort(15, 8, 4, 10, 10, "", this));
Почему buttonId==15? Откуда это магическое число?

2020-10-03 23:33 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +public class EMTextField extends GuiTextField
Вау, просмотр рецептов нажатию [R] работает отлично!

2020-10-04 04:11 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/GuiButtonSort.java
> +            EMCreativeTab.Sort = (EMCreativeTab.Sort + 1) % 4;
Попробуй разместить таковые на готовом меню.... Я не понимаю где.

2020-10-04 04:12 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/util/GuiContainerCreativeEM.java
> +        buttonList.add(new GuiButtonSort(15, 8, 4, 10, 10, "", this));
ну я добавила кнопку с id == 15

2020-10-04 04:13 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/init/EMEvents.java
> +            event.getButtonList().add(new GuiButtonSort(15, 8, 4, 10, 10, "", (GuiContainerCreative) event.getGui()));
Это отработала моя любовь к отсылкам. Это не не кнопка 15, а пятнадцатая кнопка) Как по мне отсылка безобидная(да и никому не понятная).

2020-10-04 04:17 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +    public EMTextField(int componentId, FontRenderer fontrendererObj, int x, int y, int width, int height, GuiContainerCreative gui)
Могу сделать светлой, но нужно будет еще по +-5 полям АТ пройтись.

2020-10-04 04:27 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +public class EMTextField extends GuiTextField
Не зря же на это потрачено столько же времени сколько на все остальное)

2020-10-04 04:45 UTC, GoogeTan commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +    public EMTextField(int componentId, FontRenderer fontrendererObj, int x, int y, int width, int height, GuiContainerCreative gui)
Ошиблась) 2 строчками)

2020-10-04 09:15 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/GuiButtonSort.java
> +            EMCreativeTab.Sort = (EMCreativeTab.Sort + 1) % 4;
Например, как на эскизе: сделать текстовое поле короче в два раза и на освободившемся месте разместить кнопки
![image](https://user-images.githubusercontent.com/35610168/95011701-4e370d80-063b-11eb-8642-64f89dbd5e2d.png)

2020-10-04 09:17 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/init/EMEvents.java
> +            event.getButtonList().add(new GuiButtonSort(15, 8, 4, 10, 10, "", (GuiContainerCreative) event.getGui()));
Ок, надеюсь, не заколлизится с какими-то другими кнопками

2020-12-12 13:13 UTC, hohserg1 approved these changes

2020-12-12 13:17 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +public class EMTextField extends GuiTextField
Нашел баг: если переключить с нашей вкладки на другую, то текстовое поле переходит в фокус

2020-12-12 13:18 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +public class EMTextField extends GuiTextField
![CPNixMjwbT](https://user-images.githubusercontent.com/35610168/101984952-ade21280-3c95-11eb-813e-76bda67d6e50.gif)

2020-12-12 13:26 UTC, hohserg1 commented on src/main/scala/ru/mousecray/endmagic/client/gui/elements/EMTextField.java
> +public class EMTextField extends GuiTextField
Пофиксил

2020-12-12 13:34 UTC, merged